repos:
- repo: https://github.com/pycqa/isort
  rev: "5.10.1"
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
  - id: black
    language_version: python3.9

- repo: https://github.com/myint/docformatter
  rev: v1.4
  hooks:
    - id: docformatter
      args: [--blank, --in-place, --recursive, --wrap-descriptions=70, --wrap-summaries=80]

- repo: https://github.com/pycqa/pylint
  rev: v2.12.2
  hooks:
  - id: pylint
    additional_dependencies: [pytest, numpy, plotly]